version: "3.6"

services:
  user-service:
    container_name: user_service
    build:
      context: services
      dockerfile: user-service.dockerfile
    networks:
      - backend
    ports:
      - "8000:8000"
    env_file:
      - jwt.env
      - user-db.env
    depends_on:
      - algo-service
      - user-db

  algo-service:
    container_name: algo_service
    build:
      context: services
      dockerfile: algo-service.dockerfile
    networks:
      - backend
    env_file:
      - algo-db.env
    ports:
      - "8001:8000"
    depends_on:
      - algo-db

  ui-service:
    container_name: ui_service
    build:
      context: services/ui_service
      dockerfile: ui-service.dockerfile
    networks:
      - backend
    ports:
      - "5001:5001"
    depends_on:
      - user-service
  
  user-db:
    container_name: user_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: "user_db"
      POSTGRES_USER: "hisa-user"
      POSTGRES_PASSWORD: "LAhOGLC/vHwxXK4RCFD7Qn54+ek="  # FIXME
    networks:
      - backend
    ports:
      - "5432:5432"
  
  algo-db:
    container_name: algo_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: "algo_db"
      POSTGRES_USER: "hisa-user"
      POSTGRES_PASSWORD: "66I50dYw7EOM4+FKPRxazHTKLS4="  # FIXME
    networks:
      - backend
    ports:
      - "5433:5432"

networks:
  backend:
