version: "3.6"

services:
  user-service:
    container_name: user_service
    build:
      context: services/user_service
      dockerfile: user-service.dockerfile
    networks:
      - default
    ports:
      - "8000:8000"
