version: "3.6"

services:
  user-service:
    container_name: user_service
    build:
      context: services/user_service
      dockerfile: user-service.dockerfile
    networks:
      - backend
    ports:
      - "8000:8000"
    env_file:
      - jwt.env
    depends_on:
      - algo-service

  algo-service:
    container_name: algo_service
    build:
      context: services/algo_service
      dockerfile: algo-service.dockerfile
    networks:
      - backend
    ports:
      - "8001:8000"

  ui-service:
    container_name: ui_service
    build:
      context: services/ui_service
      dockerfile: ui-service.dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  backend:
