version: "3.6"

services:
  user-server:
    container_name: user-server
    build:
      context: ./server
      dockerfile: user-server.dockerfile
    networks:
      - default
    ports:
      - "8000:8000"
