name: Run integration tests

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up the Docker repository
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin   

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Run Docker
      run: |
        docker compose up -d

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest requests

    - name: Check services healthiness
      uses: thegabriele97/dockercompose-health-action@main
      with:
        timeout: '90'
        workdir: '.'

    - name: Run algo integration tests
      run: |
        python -m pytest test/test_integration/test_algo

    - name: Run user integration tests
      run: |
        python -m pytest test/test_integration/test_user
